package com.hyphenate.easeui.model;

import com.hyphenate.easeui.R;
import com.hyphenate.easeui.domain.EaseEmojicon;
import com.hyphenate.easeui.domain.EaseEmojicon.Type;
import com.hyphenate.easeui.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {
    
    private static String[] emojis = new String[]{
            EaseSmileUtils.expression_1,
            EaseSmileUtils.expression_2,
            EaseSmileUtils.expression_3,
            EaseSmileUtils.expression_4,
            EaseSmileUtils.expression_5,
            EaseSmileUtils.expression_6,
            EaseSmileUtils.expression_7,
            EaseSmileUtils.expression_8,
            EaseSmileUtils.expression_9,
            EaseSmileUtils.expression_10,
            EaseSmileUtils.expression_11,
            EaseSmileUtils.expression_12,
            EaseSmileUtils.expression_13,
            EaseSmileUtils.expression_14,
            EaseSmileUtils.expression_15,
            EaseSmileUtils.expression_16,
            EaseSmileUtils.expression_17,
            EaseSmileUtils.expression_18,
            EaseSmileUtils.expression_19,
            EaseSmileUtils.expression_20,
            EaseSmileUtils.expression_21,
            EaseSmileUtils.expression_22,
            EaseSmileUtils.expression_23,
            EaseSmileUtils.expression_24,
            EaseSmileUtils.expression_25,
            EaseSmileUtils.expression_26,
            EaseSmileUtils.expression_27,
            EaseSmileUtils.expression_28,
            EaseSmileUtils.expression_29,
            EaseSmileUtils.expression_30,
            EaseSmileUtils.expression_31,
            EaseSmileUtils.expression_32,
            EaseSmileUtils.expression_33,
            EaseSmileUtils.expression_34,
            EaseSmileUtils.expression_35,
            EaseSmileUtils.expression_36,
            EaseSmileUtils.expression_37,
            EaseSmileUtils.expression_38,
            EaseSmileUtils.expression_39,
            EaseSmileUtils.expression_40,
            EaseSmileUtils.expression_41,
            EaseSmileUtils.expression_42,
            EaseSmileUtils.expression_43,
            EaseSmileUtils.expression_44,
            EaseSmileUtils.expression_45,
            EaseSmileUtils.expression_46,
            EaseSmileUtils.expression_47,
            EaseSmileUtils.expression_48,
            EaseSmileUtils.expression_49,
            EaseSmileUtils.expression_50,
            EaseSmileUtils.expression_51,
            EaseSmileUtils.expression_52,
            EaseSmileUtils.expression_53,
            EaseSmileUtils.expression_54,
            EaseSmileUtils.expression_55,
            EaseSmileUtils.expression_56,
            EaseSmileUtils.expression_57,
            EaseSmileUtils.expression_58,
            EaseSmileUtils.expression_59,
            EaseSmileUtils.expression_60,
            EaseSmileUtils.expression_61,
            EaseSmileUtils.expression_62,
            EaseSmileUtils.expression_63,
            EaseSmileUtils.expression_64,
            EaseSmileUtils.expression_65,
            EaseSmileUtils.expression_66,
            EaseSmileUtils.expression_67,
            EaseSmileUtils.expression_68,
            EaseSmileUtils.expression_69,
            EaseSmileUtils.expression_70,
            EaseSmileUtils.expression_71,
            EaseSmileUtils.expression_72,
            EaseSmileUtils.expression_73,
            EaseSmileUtils.expression_74,
            EaseSmileUtils.expression_75,
            EaseSmileUtils.expression_76,
            EaseSmileUtils.expression_77,
            EaseSmileUtils.expression_78,
            EaseSmileUtils.expression_79,
            EaseSmileUtils.expression_80,
            EaseSmileUtils.expression_81,
            EaseSmileUtils.expression_82,
            EaseSmileUtils.expression_83,
            EaseSmileUtils.expression_84,
            EaseSmileUtils.expression_85,
            EaseSmileUtils.expression_86,
            EaseSmileUtils.expression_87,
            EaseSmileUtils.expression_88,
            EaseSmileUtils.expression_89,
            EaseSmileUtils.expression_90,
            EaseSmileUtils.expression_91,
            EaseSmileUtils.expression_92,
            EaseSmileUtils.expression_93,
            EaseSmileUtils.expression_94,
            EaseSmileUtils.expression_95,
            EaseSmileUtils.expression_96,
            EaseSmileUtils.expression_97,
            EaseSmileUtils.expression_98,
            EaseSmileUtils.expression_99,
            EaseSmileUtils.expression_100,


    };
    
    private static int[] icons = new int[]{
            R.drawable.expression_1,
            R.drawable.expression_2,
            R.drawable.expression_3,
            R.drawable.expression_4,
            R.drawable.expression_5,
            R.drawable.expression_6,
            R.drawable.expression_7,
            R.drawable.expression_8,
            R.drawable.expression_9,
            R.drawable.expression_10,
            R.drawable.expression_11,
            R.drawable.expression_12,
            R.drawable.expression_13,
            R.drawable.expression_14,
            R.drawable.expression_15,
            R.drawable.expression_16,
            R.drawable.expression_17,
            R.drawable.expression_18,
            R.drawable.expression_19,
            R.drawable.expression_20,
            R.drawable.expression_21,
            R.drawable.expression_22,
            R.drawable.expression_23,
            R.drawable.expression_24,
            R.drawable.expression_25,
            R.drawable.expression_26,
            R.drawable.expression_27,
            R.drawable.expression_28,
            R.drawable.expression_29,
            R.drawable.expression_30,
            R.drawable.expression_31,
            R.drawable.expression_32,
            R.drawable.expression_33,
            R.drawable.expression_34,
            R.drawable.expression_35,
            R.drawable.expression_36,
            R.drawable.expression_37,
            R.drawable.expression_38,
            R.drawable.expression_39,
            R.drawable.expression_40,
            R.drawable.expression_41,
            R.drawable.expression_42,
            R.drawable.expression_43,
            R.drawable.expression_44,
            R.drawable.expression_45,
            R.drawable.expression_46,
            R.drawable.expression_47,
            R.drawable.expression_48,
            R.drawable.expression_49,
            R.drawable.expression_50,
            R.drawable.expression_51,
            R.drawable.expression_52,
            R.drawable.expression_53,
            R.drawable.expression_54,
            R.drawable.expression_55,
            R.drawable.expression_56,
            R.drawable.expression_57,
            R.drawable.expression_58,
            R.drawable.expression_59,
            R.drawable.expression_60,
            R.drawable.expression_61,
            R.drawable.expression_62,
            R.drawable.expression_63,
            R.drawable.expression_64,
            R.drawable.expression_65,
            R.drawable.expression_66,
            R.drawable.expression_67,
            R.drawable.expression_68,
            R.drawable.expression_69,
            R.drawable.expression_70,
            R.drawable.expression_71,
            R.drawable.expression_72,
            R.drawable.expression_73,
            R.drawable.expression_74,
            R.drawable.expression_75,
            R.drawable.expression_76,
            R.drawable.expression_77,
            R.drawable.expression_78,
            R.drawable.expression_79,
            R.drawable.expression_80,
            R.drawable.expression_81,
            R.drawable.expression_82,
            R.drawable.expression_83,
            R.drawable.expression_84,
            R.drawable.expression_85,
            R.drawable.expression_86,
            R.drawable.expression_87,
            R.drawable.expression_88,
            R.drawable.expression_89,
            R.drawable.expression_90,
            R.drawable.expression_91,
            R.drawable.expression_92,
            R.drawable.expression_93,
            R.drawable.expression_94,
            R.drawable.expression_95,
            R.drawable.expression_96,
            R.drawable.expression_97,
            R.drawable.expression_98,
            R.drawable.expression_99,
            R.drawable.expression_100,

    };
    
    
    private static final EaseEmojicon[] DATA = createData();
    
    private static EaseEmojicon[] createData(){
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for(int i = 0; i < icons.length; i++){
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }
    
    public static EaseEmojicon[] getData(){
        return DATA;
    }
}
